### ISSUE TITLE
Allow database content translation

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/scope#105]
With the setup of Django i18n in #16, all the interface is translatable, but the database fields are not translatable yet.

**Estimates:**
- Add translation system for database models (using [django-modeltranslation](https://github.com/deschler/django-modeltranslation)):
  - Only for the FAQ page content (after #96): 10 hours.
  - For the FAQ page and all the current data models: 60 hours (requires to include the translations into the Elasticsearch indexes too).

**Comment by stefanabreitwieser** [comment]
@jraddaoui There's no need to translate the database content, per CCA current practice. We have single-language finding aids based on the language of the collection -- this won't be changing for this project. The only things that need to be translated are all the field names and the FAQ page. So long as the FAQ can be updated in both languages, doing the string translations isn't even necessary for that. 

We'll let you know if we have any additional feedback after @mireilleN 's translations have been merged, but as of right now, I think we're satisfied with the level of translation. Thanks!

**Comment by jraddaoui** [comment]
Currently looking at other possibilities to allow translations of static content (added in #96):

- https://github.com/deschler/django-modeltranslation
- ~~https://github.com/django-parler/django-parler~~ (not compatible with Django 2.x)
- ~~https://github.com/KristianOellegaard/django-hvad~~ (not compatible with Django 2.x)
- https://github.com/matthiask/django-translated-fields

**Comment by jraddaoui** [comment]
We finally used `django-modeltranslation` to allow the translation of the page contents from #96.

This is ready for review in the test instance. Some notes about how translations work for now:

- The default language is "en".
- In the content page, one or more contents can be edited at the same time, but only in one language. The contents submitted will be saved in the current language of the application.
- There is a fallback mechanism that will show the content in the default language if the current language is not populated.

**Comment by stefanabreitwieser** [comment]
Looks great, thanks Radda! :)
