### ISSUE TITLE
UX: FAQ page shorten the line length

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/scope#146]
To be more readable from a UX perspective, can we shorten the line length to 100 characters ?

**Comment by jraddaoui** [comment]
We can give a `max-width` to the content of that page, like in the search filters. But, in my opinion, cutting content and leaving long white spaces in some pages at high resolutions is not a very good option either (even if it's centered).

I'd suggest to look for a two columns layout in this page, similar to what we have in the folders and digital files pages for the attachments section, which is displayed in one column in medium resolutions.

Also, we should address this alongside #96.

**Comment by bunekcca** [comment]
Hi @jraddaoui 

White space is not an issue to me. [Look at this](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/). If you scroll down, you've got tons of white space. The important point is just to make it readable and not let the user feel overwhelmed by the text.

**Comment by bunekcca** [comment]
Can we align the text to the left instead of having it centered ?

![image](https://user-images.githubusercontent.com/38663513/58903635-e59cf100-86d3-11e9-935e-39295554ee72.png)

**Comment by jraddaoui** [comment]
Hi @bunekcca,

As you may have noticed, HTML can be used when editing this page content, something that was done to ease the adoption of the application, among other reasons. Considering that, I think it's a good idea to remove the FAQ container I created for this work. Instead, this alignment can be achieved by using HTML in the content input, which allows to have different aspects and a lot of options for someone with knowledge of [Bootstrap 4](https://getbootstrap.com/docs/4.3/getting-started/introduction/).

For example, the current alignment in the test site is created by wrapping the content in the following elements:

```html
<div class="row">
  <div class="col-md-10 col-lg-8 col-xl-6">
  ...
  </div>
</div>
```

Please, let me know if that's okay.

**Comment by bunekcca** [comment]
Hi @jraddaoui 

I agree, way more flexible. Let's do that then.

Have a good day.

**Comment by jraddaoui** [comment]
Thanks @bunekcca! It's already done and ready for review in the test instance.

**Comment by bunekcca** [comment]
Perfect
