### ISSUE TITLE
UI: add a tooltip for the filepath

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/scope#151]
To help users finding the file within the zip downloaded, having a tooltip users can click on would be helpful. It emphasizes the usefulness of the filepath.

Default state:
![image](https://user-images.githubusercontent.com/38663513/56139431-dc5e9600-5f66-11e9-9c27-bb81960fb051.png)

Opened state:
![image](https://user-images.githubusercontent.com/38663513/56139449-e5e7fe00-5f66-11e9-96cf-10b8d2e9a038.png)

**Comment by jraddaoui** [comment]
The link icon is slightly different and I've not added the close button. Bootstrap's tool-tip behavior only leaves it open if the link is clicked and it closes the tool-tip when clicking anywhere else.
