### ISSUE TITLE
UX: button to reset all filters

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/scope#159]
Reset the filters by clicking on the X is not working for users.
Can we add a reset filters button ? (like the prototype)
![image](https://user-images.githubusercontent.com/38663513/57779832-f1108400-76f4-11e9-807c-aceefd84d1a8.png)

**Comment by seihpos** [comment]
Does the reset functionality also works if you've entered text in the field on top of the list? If so, does this location make sense?

**Comment by jraddaoui** [comment]
@seihpos: The reset link will reload the entire page, so it'll clear the content of those fields and the big input too.

@bunekcca: I'd like to know in which browsers and conditions the current X button does not work? At this point, it's just a link using `href="."`, to make it work in different places (search an folders pages). We can set the `href` attribute to the proper URL for each page to see if that's really the issue. But please, confirm if you also want it moved to that place.

**Comment by seihpos** [comment]
Thanks @jraddaoui! I'll check with Bun on Thurday (he'll be back at the CCA), and we'll get back to you.

**Comment by stefanabreitwieser** [comment]
@jraddaoui : The functionality of button works fine! It's more of a UX decision -- user's can't quite find the button or understand what it does. Having the "reset filters" button as Bun suggestions is to make the button a bit more obvious. I don't think any of the functionality of the button needs to be changed, just how it looks. Thank you!

**Comment by bunekcca** [comment]
Hi @jraddaoui,
Like @stefanabreitwieser said it's just that it's not so obvious to have the X at that place to reset all the filters. 
From a UX perspective, it's better to have it near the list of filters that have been applied.
