### ISSUE TITLE
UI: values in the dropdown sorted by alphabetical order

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/scope#160]
Could we sort the items of the lists by alphabetical order ?
![image](https://user-images.githubusercontent.com/38663513/57779919-1ef5c880-76f5-11e9-95ff-ece41c5ca0ac.png)

**Comment by jraddaoui** [comment]
Ready for review in the test instance. The order is case sensitive, which I think it's not ideal but changing that will require to modify how the related fields are analyzed by Elasticsearch and probably how the aggregation query is done, something that may take between 4 and 8 hours of work.
