### ISSUE TITLE
Merge scope and dips core apps into scope

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/scope#167]
See https://github.com/CCA-Public/scope/pull/150#issuecomment-483364652.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser and @marcbouchercca,

This work has been merged in the master branch and it's ready for review. Please, make sure that the database is fully recreated in the next upgrade you make in your instance. Just remove the `db.sqlite3` file before running all the commands I sent you to upgrade and create a new superuser.

**Comment by stefanabreitwieser** [comment]
Thank you!!
