### ISSUE TITLE
Automated upload from Archivematica and DIP storage

### ISSUE THREAD

**Issue by tw4l** [CCA-Public/scope#2]
* Will require REST endpoint in application  - use django-rest-framework with MultiPartParser to send DIP and identifier/collection separately as metadata?  
* See [Archivematica AtoM upload script](https://github.com/artefactual/archivematica/blob/92d7abd238585e64e6064bc3f1ddfc663c4d3ace/src/MCPClient/lib/clientScripts/upload-qubit.py)

**Comment by jraddaoui** [comment]
This will require further analysis alongside #2, #98 and #17. A possible workflow will be presented in tomorrow's meeting, which will probably require changes in the SS, the automation tools and this project. We should estimate after discussing and refining that workflow.

**Comment by jraddaoui** [comment]
Moved here from #98 (now closed):

> From user stories (IT, round 2)
> - As local IT, I want to reduce redundant DIP storage by integrating SCOPE and Archivematica.

The duplication should be addressed alongside this issue.

**Comment by stefanabreitwieser** [comment]
Do we have a rough time estimate for this? It's a high priority for phase 2, so it's important that we account for it as we plan for the next round of work. Thanks!!
