### ISSUE TITLE
Users should be able to edit their own account

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/scope#56]
Currently, Managers and Administrators can edit all users but Editors and Viewers don't have access to the manage user pages.

An "Edit account" link should be added to the user drop-down to allow access to all users to their own edit user form to change their personal data. This form should not include the "Active", "Administrator" and "Groups" fields if the user is an Editor or a Viewer.

**Comment by jraddaoui** [comment]
Estimate: 8 hours.

**Comment by jraddaoui** [comment]
Added a "Profile" link to the header drop-down that leads the user to the user edit page and form. In that case, the form will not include the administrator, active and groups fields.

**Comment by bunekcca** [comment]
OK
