### ISSUE TITLE
A manager shouldn't be able to edit an admin account

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/scope#60]
An admin account should be only edited by an admin.

**Comment by jraddaoui** [comment]
**Estimate: 1 h**

**Comment by jraddaoui** [comment]
A manager will still see the administrator in the users table but the "See more" button won't be present for them and the direct access to an admin page is also forbidden (redirect to the users page).

**Comment by bunekcca** [comment]
Hi @jraddaoui 
Is it possible to hide the users that you can't edit instead of just hiding the button ?
UX-wise it would be better to hide what you can't have action on.

**Comment by jraddaoui** [comment]
@bunekcca, done!

**Comment by bunekcca** [comment]
Perfect
