### ISSUE TITLE
Problem: cannot update the FAQ page

### ISSUE THREAD

**Issue by kellyannewithane** [CCA-Public/scope#96]
From the user stories (administrator, round 2)

-As the Administrator, I want to edit the FAQ page to update the information found there.

**Comment by jraddaoui** [comment]
A settings page will be added to the application in #7. A new section could be included in that page to edit the FAQ content. With the setup of Django i18n in #16, all the interface is translatable, but the database fields are not translatable yet. Making this editable and moving it's content will require to integrate a model translation mechanism, which should also be used for some Dublin Core metadata and other models at some point.

**Estimates:**
- Add FAQ content (text area field) to a new section in the settings page:
  - Allowing HTML: 8 hours.
  - Allowing Markdown syntax: 16 hours.
- Add translation system for database models (using [django-modeltranslation](https://github.com/deschler/django-modeltranslation)):
  - Only for the FAQ page content: 12 hours.
  - For the FAQ page and all the current data models: 40 hours.

**Comment by stefanabreitwieser** [comment]
I was also thinking that the text should be customizable by administrators in two other places. 

The homepage (highlighted): 
![image](https://user-images.githubusercontent.com/31662214/55578334-a528f300-56e3-11e9-8757-ea12ed6d7618.png)

And the login page (also highlighted): 
![image](https://user-images.githubusercontent.com/31662214/55578419-dc979f80-56e3-11e9-82de-9d49e08ddb57.png)

I think this would make SCOPE more usable for potential non-CCA adopters. We'll keep this issue in the backlog for now, but just noting that the scope of this issue should be expanded somewhat. Thanks!

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui, I think the markdown option would be better. Thanks!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser,

Please note that, to allow updating the FAQ and other pages in multiple languages, we'll need to do the lower estimate of #105.

Also, for new installations, what should be the default content in those pages? Should we use the text we already have or would you like to create something more generic or leave them empty?

**Comment by stefanabreitwieser** [comment]
No problem -- thanks for letting me know! For the default content, I think the FAQ page and "Policies for use of born-digital material at CCA" page should be blank. I think "Digital Archives Access Interface" text on the homepage is okay as it is now. 

Thanks Radda!

**Comment by jraddaoui** [comment]
This is ready for review in the test site.

There is a new "Content" link in the header drop-down, only accessible for administrators. The content page will let you edit the contents outlined above in both Markdown and/or HTML. I'll add some notes about the content translation in #105.

In a new installation, the FAQ page and the content bellow the login form will be empty and the home page content will have the values you'll see in the content page. In the test instance, I have already edited the empty contents with the HTML we had for both languages, to keep it as it was before, but feel free to modify those contents and use Markdown on them.

**Comment by jraddaoui** [comment]
Also, I've created #164 to validate and store the rendered Markdown in the database, to speed up the page load a bit.

**Comment by stefanabreitwieser** [comment]
Works! Thank you :)
